INSERT INTO AVATAR VALUES (1, 'Ana', 100.0);
INSERT INTO AVATAR VALUES (2, 'Betina', 1000.0);
INSERT INTO AVATAR VALUES (3, 'Carol', 10000.0);

INSERT INTO EQUIPAMENTO VALUES (1, 'Vestido Rosa', 100.0,  'Corpo');
INSERT INTO EQUIPAMENTO VALUES (2, 'Vestido Amarelo', 1000.0,  'Corpo');
INSERT INTO EQUIPAMENTO VALUES (3, 'Vestido Roxo', 10000.0,  'Corpo');

INSERT INTO EQUIPAMENTO VALUES (4, 'Franja 1', 100.0,  'Cabelo');
INSERT INTO EQUIPAMENTO VALUES (5, 'Franja 2', 1000.0,  'Cabelo');
INSERT INTO EQUIPAMENTO VALUES (6, 'Franja 3', 10000.0,  'Cabelo');

INSERT INTO EQUIPAMENTO VALUES (7, 'Chinelo Azul', 100.0,  'Sapato');
INSERT INTO EQUIPAMENTO VALUES (8, 'Meia Cinza', 1000.0,  'Sapato');
INSERT INTO EQUIPAMENTO VALUES (9, 'Sandália Rosa', 10000.0,  'Sapato');