INSERT INTO AVATAR VALUES (1, 'Ana', 100.0);
INSERT INTO AVATAR VALUES (2, 'Beto', 1000.0);
INSERT INTO AVATAR VALUES (3, 'Carol', 10000.0);

INSERT INTO EQUIPAMENTO VALUES (1, 'Armadura de Couro', 100.0,  'Corpo');
INSERT INTO EQUIPAMENTO VALUES (2, 'Cota de Malha', 1000.0,  'Corpo');
INSERT INTO EQUIPAMENTO VALUES (3, 'Armadura Lendária', 10000.0,  'Corpo');